# Generated by Django 4.0 on 2022-07-27 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0002_tag_created_on_alter_tag_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('comment', models.TextField()),
                ('title', models.CharField(max_length=33)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='auth.user')),
                ('stars', models.ManyToManyField(related_name='stared_reviews', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='reviews', to='tags.Tag')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
