# Generated by Django 4.0.6 on 2022-08-04 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('comment', models.TextField()),
                ('title', models.CharField(max_length=33)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('stars', models.ManyToManyField(related_name='stared_reviews', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='reviews', to='tags.tag')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
