# Generated by Django 4.0.6 on 2022-08-04 09:53

import autoslug.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.UUIDField(unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='label', unique_with=('id',))),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('followers', models.ManyToManyField(related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
