# Generated by Django 4.0 on 2022-07-26 12:13

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=30, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='label', unique_with=('id',))),
                ('followers', models.ManyToManyField(related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
